
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moklet
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        perempuan = new javax.swing.JRadioButton();
        laki = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        clear1 = new javax.swing.JButton();
        refresh1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("The Real Informatic School");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 50, 360, 40);

        jLabel2.setFont(new java.awt.Font("Square721 Cn BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM BIODATA SMK TELKOM MALANG");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 760, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 100);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
        jLabel3.setText("NIS");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 40, 40, 20);

        nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nisActionPerformed(evt);
            }
        });
        jPanel2.add(nis);
        nis.setBounds(20, 70, 180, 30);

        jLabel4.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
        jLabel4.setText("Nama");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 110, 40, 20);
        jPanel2.add(nama);
        nama.setBounds(20, 140, 260, 30);

        jLabel5.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 180, 100, 20);
        jPanel2.add(kelas);
        kelas.setBounds(20, 270, 100, 30);

        jLabel6.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
        jLabel6.setText("Kelas");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 240, 40, 20);

        buttonGroup1.add(perempuan);
        perempuan.setText("Perempuan");
        jPanel2.add(perempuan);
        perempuan.setBounds(140, 210, 120, 23);

        buttonGroup1.add(laki);
        laki.setText("Laki-laki");
        jPanel2.add(laki);
        laki.setBounds(20, 210, 110, 23);

        jLabel7.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
        jLabel7.setText("Email");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 310, 40, 20);
        jPanel2.add(email);
        email.setBounds(20, 340, 260, 30);

        jLabel8.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
        jLabel8.setText("Alamat");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 380, 40, 20);

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 400, 240, 110);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 110, 300, 540);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(null);

        edit.setFont(new java.awt.Font("Myriad Hebrew", 0, 12)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit);
        edit.setBounds(420, 20, 90, 30);

        save.setFont(new java.awt.Font("Myriad Hebrew", 0, 12)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save);
        save.setBounds(20, 20, 90, 30);

        delete1.setFont(new java.awt.Font("Myriad Hebrew", 0, 12)); // NOI18N
        delete1.setText("Delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel3.add(delete1);
        delete1.setBounds(120, 20, 90, 30);

        clear1.setFont(new java.awt.Font("Myriad Hebrew", 0, 12)); // NOI18N
        clear1.setText("Clear");
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });
        jPanel3.add(clear1);
        clear1.setBounds(220, 20, 90, 30);

        refresh1.setFont(new java.awt.Font("Myriad Hebrew", 0, 12)); // NOI18N
        refresh1.setText("Refresh");
        refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1ActionPerformed(evt);
            }
        });
        jPanel3.add(refresh1);
        refresh1.setBounds(320, 20, 90, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(320, 110, 530, 70);

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setLayout(null);

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Kelas", "Email", "Alamat"
            }
        ));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(data);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 11, 510, 440);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(320, 190, 530, 460);

        setSize(new java.awt.Dimension(874, 703));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       if("".equals(nis.getText()) || "".equals(alamat.getText()) || "".equals(kelas.getText()) ||  "".equals(nama.getText()) || "".equals(email.getText()))
       {
        JOptionPane.showMessageDialog(this,"Harap lengkapi data","Error", JOptionPane.WARNING_MESSAGE);
    }else{
           String JK = "";
           if(laki.isSelected()){
               JK=  "L";
           }else{
               JK = "P";
           }
           String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat)" + "VALUES('"+nis.getText()+"','"+nama.getText()+"','"+JK+"','"+kelas.getText()+"','"+email.getText()+"','"+alamat.getText()+"')";
           int status = KoneksiDB.execute(SQL);
           if(status == 1){
               JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
               selectData();
           } else{
              JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Error", JOptionPane.WARNING_MESSAGE); 
           }
       }
    }//GEN-LAST:event_saveActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        int baris = data.getSelectedRow();
        if(baris !=  -1){
            String NIS = data.getValueAt(baris,0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS = '"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
        
        if(status == 1){
             JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE); 
        }else{
            JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Error", JOptionPane.WARNING_MESSAGE); 
        }  
        }else{
            JOptionPane.showMessageDialog(this, "Pilih baris terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);     
        }
    }//GEN-LAST:event_delete1ActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        nama.setText("");
        nis.setText("");
        kelas.setText("");
        buttonGroup1.clearSelection();
        email.setText("");
        alamat.setText("");
        
    }//GEN-LAST:event_clear1ActionPerformed

    private void refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1ActionPerformed
        selectData();
        
    }//GEN-LAST:event_refresh1ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        if("".equals(nis.getText()) || "".equals(alamat.getText()) || "".equals(kelas.getText()) ||  "".equals(nama.getText()) || "".equals(email.getText()))
       {
        JOptionPane.showMessageDialog(this,"Harap lengkapi data","Error", JOptionPane.WARNING_MESSAGE);
    }else{
           String JK = "";
           if(laki.isSelected()){
               JK=  "L";
           }else if(perempuan.isSelected()){
               JK = "P";
           }else{
                   JK = "Belum Diisi";
                   }
           
         String SQL = "UPDATE t_siswa SET NIS='"+nis.getText()+"',NamaSiswa='"+nama.getText()+"',JenisKelamin='"+JK+"',Kelas='"+kelas.getText()+"',Email='"+email.getText()+"',Alamat = '"+alamat.getText()+"'WHERE NIS = '"+nis.getText()+"' ";
         //cek string SQL               
         int status = KoneksiDB.execute(SQL);
         if (status == 1){ //cek en ininya
        JOptionPane.showMessageDialog(this,"Data berhasil di update","Sukses", JOptionPane.INFORMATION_MESSAGE);
    selectData();
         }else{
                    JOptionPane.showMessageDialog(this,"Data gagal diupdate","Error", JOptionPane.WARNING_MESSAGE);
                    }
            } 
         
         
    }//GEN-LAST:event_editActionPerformed

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
       int baris = data.getSelectedRow();
       if(baris != -1){
           nis.setText(data.getValueAt(baris, 0 ).toString());
           nama.setText(data.getValueAt(baris, 1 ).toString());
           if("Laki-laki".equals(data.getValueAt(baris, 2).toString())){
               laki.setSelected(true);
           }else{
               perempuan.setSelected(true);
           }
            kelas.setText(data.getValueAt(baris, 3 ).toString());
            email.setText(data.getValueAt(baris, 4 ).toString());
            alamat.setText(data.getValueAt(baris, 5 ).toString());
       }
    }//GEN-LAST:event_dataMouseClicked

    private void nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nisActionPerformed

    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear1;
    private javax.swing.JTable data;
    private javax.swing.JButton delete1;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kelas;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton refresh1;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

    public void selectData() {
      String kolom[]  = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
      DefaultTableModel dtm = new DefaultTableModel(null,kolom);
      String SQL = "SELECT * FROM t_siswa";
      ResultSet rs = KoneksiDB.executeQuery(SQL);
      try{
          while(rs.next()){
              String NIS = rs.getString(1);
              String NamaSiswa = rs.getString(2);
              String JenisKelamin = "";
              if("L".equals(rs.getString(3))){
                  JenisKelamin = "Laki-laki";
              }
              else{
                  JenisKelamin = "Perempuan";
              }
              String Kelas = rs.getString(4);
              String Email = rs.getString(5);
              String Alamat = rs.getString(6);
              String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
              dtm.addRow(data);
          }
      }catch(SQLException ex){
          Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
      }
      data.setModel(dtm);
    }
}
